# Generated by Django 5.0.4 on 2024-04-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalperformance',
            old_name='avarage_response_time',
            new_name='average_response_time',
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='avarage_response_time',
            new_name='average_response_time',
        ),
    ]
